services:

  bff-jvm: &bff-jvm
    image: docker.io/adrianomoreira86/quarkus-demo-bff:jvm-21-quarkus-3.15
    profiles:
      - jvm
    ports:
      - "9001:8080"
    deploy:
      resources:
        limits:
          memory: 1GB
          cpus: 1.0
    environment:
      # quarkus.http.access-log.enabled: true
      quarkus.log.level: WARN
      quarkus.rest-client.ms1.url: http://ms1-jvm:8080

  ms1-jvm: &ms1-jvm
    image: docker.io/adrianomoreira86/quarkus-demo-ms1:jvm-21-quarkus-3.15
    profiles:
      - jvm
    ports:
      - "9002:8080"
    deploy:
      resources:
        limits:
          memory: 1GB
          cpus: 1.0
    environment:
      # quarkus.http.access-log.enabled: true
      quarkus.log.level: WARN
      quarkus.datasource.db-kind: postgresql
      quarkus.datasource.jdbc.url: jdbc:postgresql://postgres:5432/db_name
      quarkus.datasource.reactive.url: vertx-reactive:postgresql://postgres:5432/db_name
      quarkus.datasource.username: admin
      quarkus.datasource.password: admin
      quarkus.redis.hosts: redis://redis:6379



  bff-native:
    <<: *bff-jvm
    image: docker.io/adrianomoreira86/quarkus-demo-bff:native-21-quarkus-3.15
    profiles:
      - native
    ports:
      - "9003:8080"
    environment:
      # quarkus.http.access-log.enabled: true
      quarkus.log.level: WARN
      quarkus.rest-client.ms1.url: http://ms1-native:8080


  ms1-native:
    <<: *ms1-jvm
    image: docker.io/adrianomoreira86/quarkus-demo-ms1:native-21-quarkus-3.15
    profiles:
      - native

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: "db_name"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"

  redis:
    image: redis:7.2-alpine